# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oy2vdgK-a2xJDG6kyHfRWuqqUb5o0anQ
"""

import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from xgboost import XGBClassifier

data = pd.read_csv('https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3.csv')
data['DateTime'] = pd.to_datetime(data['DateTime'])
data['day'] = data['DateTime'].dt.day
data['month'] = data['DateTime'].dt.month
data['year'] = data['DateTime'].dt.year
data['hour'] = data['DateTime'].dt.hour
data = data.drop('id', axis = 'columns')
data = data.drop('DateTime', axis = 'columns')

Y = data['meal']
X = data.drop('meal', axis = 'columns')

model = XGBClassifier(n_estimators=140, max_depth=15, learning_rate=0.5)

modelFit = model.fit(X, Y)

tdata = pd.read_csv('https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3test.csv')
tdata['DateTime'] = pd.to_datetime(tdata['DateTime'])
tdata = tdata.drop('id', axis = 'columns')
tdata['day'] = tdata['DateTime'].dt.day
tdata['month'] = tdata['DateTime'].dt.month
tdata['year'] = tdata['DateTime'].dt.year
tdata['hour'] = tdata['DateTime'].dt.hour
tdata = tdata.drop('DateTime', axis = 'columns')

Xt = tdata.drop('meal', axis = 'columns')

pred = model.predict(Xt)