# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fxt1ObzwklrvoCQlMgfkpAxQAb0XSH55
"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import patsy as pt

data = pd.read_csv('https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3.csv')
data['DateTime'] = pd.to_datetime(data['DateTime'])
data = data.drop('id', axis = 'columns')
data['day'] = data['DateTime'].dt.day
data['month'] = data['DateTime'].dt.month
data['year'] = data['DateTime'].dt.year
data['hour'] = data['DateTime'].dt.hour
data = data.drop('DateTime', axis = 'columns')

Y = data['meal']
X = data.drop('meal', axis = 'columns')

# Commented out IPython magic to ensure Python compatibility.
model = DecisionTreeClassifier()

modelFit = model.fit(X,Y)

print("\n\nIn-sample accuracy: %s%%\n\n"
#  % str(round(100*accuracy_score(Y, model.predict(X)), 2)))

test_data = pd.read_csv('https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3test.csv')
test_data['DateTime'] = pd.to_datetime(test_data['DateTime'])
test_data = test_data.drop('id', axis = 'columns')
test_data['day'] = test_data['DateTime'].dt.day
test_data['month'] = test_data['DateTime'].dt.month
test_data['year'] = test_data['DateTime'].dt.year
test_data['hour'] = test_data['DateTime'].dt.hour
test_data = test_data.drop('DateTime', axis = 'columns')

test_X = test_data.drop('meal', axis = 'columns')

pred = model.predict(test_X)